# Generated by Django 3.2.12 on 2022-05-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0003_alter_trending_pub_date'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='trendnews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trendnews_comments', to='trending.trending'),
        ),
    ]
