# Generated by Django 3.2.12 on 2022-05-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0002_alter_trending_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
