# Generated by Django 3.2.12 on 2022-05-23 13:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0003_alter_trending_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='short_txt',
        ),
        migrations.AlterField(
            model_name='trending',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='profile_image'),
        ),
    ]
