# Generated by Django 3.2.12 on 2022-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0004_auto_20220523_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='short_txt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
