# Generated by Django 3.2.12 on 2022-06-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0006_auto_20220601_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='image',
        ),
    ]
