# Generated by Django 3.2.12 on 2022-06-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0007_remove_trending_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
