# Generated by Django 3.2.12 on 2022-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0008_trending_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
