# Generated by Django 3.2.12 on 2022-06-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0009_alter_trending_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='tags',
        ),
        migrations.DeleteModel(
            name='UUIDTaggedItem',
        ),
    ]
