# Generated by Django 3.2.12 on 2022-06-15 10:39

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('trending', '0010_auto_20220615_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
