# Generated by Django 3.2.12 on 2022-05-22 07:34

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_auto_20220520_1400'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_txt', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.MinLengthValidator(58)])),
                ('body_txt', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(null=True)),
                ('slug', models.SlugField(default='ibmn_news', null=True, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='profile_image')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.subcategory')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
