# Generated by Django 3.2.12 on 2022-05-30 11:19

from django.db import migrations, models
import embed_video.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateTimeField(null=True)),
                ('video_url', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
