# Generated by Django 3.2.12 on 2022-06-01 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220601_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_txt',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(60)]),
        ),
    ]
