# Generated by Django 3.2.12 on 2022-06-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_short_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
