# Generated by Django 3.2.12 on 2022-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breaking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='breaking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-02-27'),
            preserve_default=False,
        ),
    ]
