# Generated by Django 3.2.12 on 2022-06-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaking', '0002_auto_20220502_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
