# Generated by Django 3.2.12 on 2022-05-20 14:42

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_auto_20220520_1400'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bignews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_txt', models.CharField(blank=True, max_length=65, null=True, validators=[django.core.validators.MinLengthValidator(60)])),
                ('body_txt', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(null=True)),
                ('slug', models.SlugField(default='ibmn', null=True, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='profile_image')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bignews_categories', to='categories.category')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
