# Generated by Django 3.2.12 on 2022-05-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bignews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bignews',
            old_name='category_name',
            new_name='category',
        ),
    ]
