# Generated by Django 3.2.12 on 2022-06-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bignews', '0003_auto_20220601_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bignews',
            name='image',
        ),
    ]
