# Generated by Django 3.2.12 on 2022-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bignews', '0004_remove_bignews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bignews',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
