# Generated by Django 3.2.12 on 2022-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bignews', '0005_bignews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bignews',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
