# Generated by Django 3.2.12 on 2022-06-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bignews', '0006_alter_bignews_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bignews',
            old_name='category',
            new_name='category_name',
        ),
    ]
