# Generated by Django 3.2.12 on 2022-06-15 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bignews', '0007_rename_category_bignews_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bignews',
            old_name='category_name',
            new_name='category',
        ),
    ]
